### PR TITLE
Update telemetry validation

### PR DESCRIPTION
**Pull request by DavidWells**

### CODE REVIEW

**Comment by bcomnes** [comment]
Can you rebase so tests pass?

**Comment by sw-yx** [comment]
rebased

**Comment by DavidWells** [comment]
After this merges we need to bump https://github.com/netlify/netlify-dev-plugin/blob/master/package.json#L8 (unless semver does its thing) 

and merge the PR here https://github.com/netlify/netlify-dev-plugin/pull/49 and it will go live

**Comment by bcomnes** [comment]
We can rely on semver so long as its compatible with both arrangements.  Otherwise we need to raise the semver floor here.  Want to land that plugin change and bump the floor?

**Pull request merged**
